site_name: Prompt Templates
site_description: A library for working with prompt templates locally or on the Hugging Face Hub
site_url: https://moritzlaurer.github.io/prompt_templates/
repo_url: https://github.com/MoritzLaurer/prompt_templates
repo_name: moritzlaurer/prompt_templates

nav:
  - Home: 
    - Overview: index.md
    - Create a Prompt Template: create_template.md
    - Standard Prompt Format: standard_prompt_format.md
    - HF Hub Repo Types: repo_types_examples.md
    - PromptTemplateDictionaries: template_dictionaries.md
    #- Tools: standard_tool_format.md
    #- Agents: agents.md
  - API Reference:
    - Prompt templates: reference/prompt_templates.md
    - Utility functions: reference/utils.md
    - Populating templates: reference/populators.md
    - PromptTemplateDictionaries: reference/template_dictionaries.md
    #- Tools: reference/tools.md

theme:
  name: material
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.indexes
    - navigation.top
    - search.suggest
    - search.highlight
    - content.tabs.link
    - content.code.annotation
    - content.code.copy
    - content.code.strip_repl_prompts  # feature does not exist?
    - navigation.footer
    - navigation.instant
    - navigation.tracking
    - toc.follow
    - header.autohide
  
  # Update color scheme to match HF style
  palette:
    # Light mode
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    # Dark mode - matches HF's dark theme
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: custom
      accent: custom
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  
  icon:
    repo: fontawesome/brands/github


extra_css:
  - stylesheets/extra.css

extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MoritzLaurer/prompt_templates
    - icon: fontawesome/brands/python
      link: https://pypi.org/project/prompt-templates/

markdown_extensions:
  - pymdownx.highlight:
      use_pygments: true
      anchor_linenums: true  
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - admonition
  - pymdownx.details

plugins:
  - search
  - autorefs
  - mkdocstrings:
      default_handler: python
      handlers:
        python:
          options:
            docstring_style: google
            show_source: true
            show_root_heading: true
            show_object_full_path: false
            heading_level: 2
            members_order: source
            separate_signature: true
            filters: ["!^_[^_]"]
            docstring_section_style: table
            render_plugin: "autorefs"

extra_javascript:
  - javascripts/strip_repl.js
